// ── Application Route Constants ────────────────────────────────────────────────
export const ROUTES = {
  HOME:            '/',
  ABOUT:           '/about',
  NGO_SOLUTIONS:   '/ngo-solutions',
  BUSINESS_SOLUTIONS: '/business-solutions',
  SERVICES:        '/services',
  SERVICE_DETAIL:  '/services/:slug',
  PORTFOLIO:       '/portfolio',
  PORTFOLIO_DETAIL:'/portfolio/:slug',
  CASE_STUDIES:    '/case-studies',
  CASE_STUDY_DETAIL:'/case-studies/:slug',
  BLOG:            '/blog',
  BLOG_DETAIL:     '/blog/:slug',
  CAREERS:         '/careers',
  CONTACT:         '/contact',
  LOGIN:           '/admin/login',

  ADMIN: {
    ROOT:           '/admin',
    DASHBOARD:      '/admin',
    SERVICES:       '/admin/services',
    SERVICE_NEW:    '/admin/services/new',
    SERVICE_EDIT:   '/admin/services/:id/edit',
    PORTFOLIO:      '/admin/portfolio',
    PORTFOLIO_NEW:  '/admin/portfolio/new',
    PORTFOLIO_EDIT: '/admin/portfolio/:id/edit',
    BLOG:           '/admin/blog',
    BLOG_NEW:       '/admin/blog/new',
    BLOG_EDIT:      '/admin/blog/:id/edit',
    TEAM:           '/admin/team',
    TESTIMONIALS:   '/admin/testimonials',
    CONTACTS:       '/admin/contacts',
    NEWSLETTER:     '/admin/newsletter',
    CAREERS:        '/admin/careers',
    MEDIA:          '/admin/media',
    SETTINGS:       '/admin/settings',
    PROFILE:        '/admin/profile',
  },
} as const;
